version: '3'
services:
  puppeteer:
    image: node:18.12.1
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    working_dir: /app
    # environment:
    #   - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    #   - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    #   - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
