version: '3'
services:
  web:
    image: ghcr.io/puppeteer/puppeteer:19.3.0
    expose:
      - 8080
    ports:
      - ${DOCKER_PORT}:8080
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
